name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: npm install
        run: npm install  
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      - name: Deployment success actor
        uses: rjstone/discord-webhook-notify@v1.0.0
        if: success() && ${{ github.event_name != 'schedule' }}
        with:
          severity: info
          details: to https://full-stack-open-pokedex-3dxz.onrender.com/ by ${{ github.actor }}
          text: A new version of Pokedex deployed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Deployment success cron
        uses: rjstone/discord-webhook-notify@v1.0.0
        if: success() && ${{ github.event_name == 'schedule' }}
        with:
          severity: info
          details: to https://full-stack-open-pokedex-3dxz.onrender.com/ by cron
          text: A new version of Pokedex deployed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Deployment failure actor
        uses: rjstone/discord-webhook-notify@v1.0.0
        if: failure() && ${{ github.event_name != 'schedule' }}
        with:
          severity: error
          details: commit ${{ github.event.head_commit.url }} by ${{ github.actor }} broke the build :(
          text: Build failed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Deployment failure cron
        uses: rjstone/discord-webhook-notify@v1.0.0
        if: failure() && ${{ github.event_name == 'schedule' }}
        with:
          severity: error          
          details: commit ${{ github.event.head_commit.url }} by cron broke the build :(
          text: Build failed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  tag_release:
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.73.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
